Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-6.7"

  config.vm.define :svr01 do |server|
    ### determined specific IP.
    server.vm.network "private_network", ip: "192.168.33.61"
    ### vbox name
    server.vm.hostname = 'hubot01'
    ### box setting
    # server.vm.box = "bento/ubuntu-15.04"
  end
  ### config.vm.define :svr02 do |server|
  ###   ### determined specific IP.
  ###   server.vm.network "private_network", ip: "192.168.33.62"
  ###   ### vbox name
  ###   server.vm.hostname = 'hubot02'
  ###   ### box setting
  ###   # server.vm.box = "bento/ubuntu-15.04"
  ### end

  config.vm.provider "virtualbox" do |vb|
    ### vagrant hostname 
    # vb.name = "hubot"
    vb.customize ['modifyvm', :id,"--memory", 512]
    vb.customize ['modifyvm', :id,"--natdnshostresolver1", "on"]
    vb.customize ['modifyvm', :id,"--natdnsproxy1", "on"]
  end  
 
  ### settitng of synced_folder
  config.vm.synced_folder "../", "/srv/base-hubot", \
    :create => true, \
    :owner  => 'root', \
    :group  => 'root', \
    :mount_options => ['dmode=777,fmode=777'] 

  # config.vm.provision :shell, :path => "ssh/init.sh"
  config.vm.provision :shell, :path => "provision.sh"

end
